### ISSUE TITLE
cache_basedir not honored in config file

### ISSUE THREAD

**Issue by millerjl1701** [drrb/puppet-library#14]
If I specify a cache_basedir in the a config file, the specified directory does not get used for proxies to cache the downloads to disk. When specified inline to launch the process, modules are cached in the specified directory. Example config file for what I would expect to use for enabling a proxy cache directory

```

---
port: 4567
daemonize: true
pidfile: /var/run/puppetlibrary.pid
cache_basedir: /var/cache/puppetlibrary
forges:
    - Directory: /var/lib/modules
    - Directory: /var/lib/other-modules
    - Proxy: http://forge.puppetlabs.com
```

I realize that the config file is an experimental feature; however, this would be a great addition to the config file as I work on puppetizing puppet-library for use in my environment. :)
